meta_product_name: "UrbanAccess"
meta_title: "UrbanAccess - L'accessibilité pour tous"
meta_description: ""
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
